/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import Tools.Imagen;
import javax.swing.JFrame;
import negocio.GenerarTramitePlacasBO;
import dto.PlacasDTO;

/**
 *
 * @author Arell
 */
public class PlacasNuevoPanel extends javax.swing.JFrame {
 private GenerarTramitePlacasBO licenciaBo;
        private PlacasDTO placa;
    /**
     * Creates new form PlacasNuevoPanel
     */
    public PlacasNuevoPanel() {
        initComponents();
        //Configurar Tamaño JFrame
        setTitle("Ventana de solicitud para Placas Nuevas");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
         // Configurar la Foto
        Imagen imagen = new Imagen();
        imagen.PintarImagen(FotoGobSonora, "src\\Pantallas\\GobSonora.jpg");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CampoCurp3 = new javax.swing.JTextField();
        Opcional = new javax.swing.JLabel();
        Curp4 = new javax.swing.JLabel();
        CampoCurp5 = new javax.swing.JTextField();
        Opcional1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        FondoGris4 = new javax.swing.JPanel();
        FotoGobSonora = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Linea = new javax.swing.JLabel();
        CampoNoSerie = new javax.swing.JTextField();
        Aceptar = new javax.swing.JButton();
        NoSerie = new javax.swing.JLabel();
        Modelo = new javax.swing.JLabel();
        CampoLinea = new javax.swing.JTextField();
        CampoModelo = new javax.swing.JTextField();
        Cancelar = new javax.swing.JButton();
        Año = new javax.swing.JLabel();
        CampoAño = new javax.swing.JTextField();
        Color = new javax.swing.JLabel();
        CampoColor = new javax.swing.JTextField();

        CampoCurp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCurp3ActionPerformed(evt);
            }
        });

        Opcional.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        Opcional.setForeground(new java.awt.Color(255, 51, 51));
        Opcional.setText("Renovar Licencia");

        Curp4.setBackground(new java.awt.Color(153, 153, 153));
        Curp4.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        Curp4.setText("Modelo");
        Curp4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Opcional1.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        Opcional1.setForeground(new java.awt.Color(255, 51, 51));
        Opcional1.setText("Vigente");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FondoGris4.setBackground(new java.awt.Color(0, 51, 51));

        FotoGobSonora.setBackground(new java.awt.Color(255, 255, 255));
        FotoGobSonora.setForeground(new java.awt.Color(255, 255, 255));
        FotoGobSonora.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setBackground(new java.awt.Color(0, 51, 51));
        jLabel4.setFont(new java.awt.Font("Roboto", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Datos del Automovil");

        javax.swing.GroupLayout FondoGris4Layout = new javax.swing.GroupLayout(FondoGris4);
        FondoGris4.setLayout(FondoGris4Layout);
        FondoGris4Layout.setHorizontalGroup(
            FondoGris4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoGris4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FotoGobSonora, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        FondoGris4Layout.setVerticalGroup(
            FondoGris4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoGris4Layout.createSequentialGroup()
                .addGroup(FondoGris4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoGris4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(FotoGobSonora, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FondoGris4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel4)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(FondoGris4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, -1));

        Linea.setBackground(new java.awt.Color(153, 153, 153));
        Linea.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        Linea.setText("Linea");
        Linea.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(Linea, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 110, -1));

        CampoNoSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNoSerieActionPerformed(evt);
            }
        });
        jPanel1.add(CampoNoSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 161, -1));

        Aceptar.setBackground(new java.awt.Color(0, 255, 51));
        Aceptar.setFont(new java.awt.Font("Roboto Black", 3, 12)); // NOI18N
        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });
        jPanel1.add(Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 112, 30));

        NoSerie.setBackground(new java.awt.Color(153, 153, 153));
        NoSerie.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        NoSerie.setText("No. Serie");
        NoSerie.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(NoSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 110, -1));

        Modelo.setBackground(new java.awt.Color(153, 153, 153));
        Modelo.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        Modelo.setText("Modelo");
        Modelo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(Modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 110, -1));

        CampoLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoLineaActionPerformed(evt);
            }
        });
        jPanel1.add(CampoLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 161, -1));

        CampoModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoModeloActionPerformed(evt);
            }
        });
        jPanel1.add(CampoModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 161, -1));

        Cancelar.setBackground(new java.awt.Color(255, 0, 0));
        Cancelar.setFont(new java.awt.Font("Roboto Black", 3, 12)); // NOI18N
        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        jPanel1.add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 101, 30));

        Año.setBackground(new java.awt.Color(153, 153, 153));
        Año.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        Año.setText("Año");
        Año.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(Año, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 110, -1));

        CampoAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoAñoActionPerformed(evt);
            }
        });
        jPanel1.add(CampoAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 161, -1));

        Color.setBackground(new java.awt.Color(153, 153, 153));
        Color.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        Color.setText("Color");
        Color.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(Color, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 110, -1));

        CampoColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoColorActionPerformed(evt);
            }
        });
        jPanel1.add(CampoColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 161, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CampoNoSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNoSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNoSerieActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
       String serie = CampoNoSerie.getText();
       String linea = CampoLinea.getText();
       String modelo = CampoModelo.getText();    
       String color =  CampoColor.getText();
       int año = Integer.getInteger(CampoAño.getText());
       if (serie.isEmpty() || linea.isEmpty() || modelo.isEmpty() || color.isEmpty() || CampoAño.getText().isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
}
        ValidarLicencia validar = new ValidarLicencia();
        validar.setVisible(true);
    }//GEN-LAST:event_AceptarActionPerformed

    private void CampoLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoLineaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoLineaActionPerformed

    private void CampoCurp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCurp3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCurp3ActionPerformed

    private void CampoModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoModeloActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // Cerrar el JFrame actual
        this.dispose();
    }//GEN-LAST:event_CancelarActionPerformed

    private void CampoAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoAñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoAñoActionPerformed

    private void CampoColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoColorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlacasNuevoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlacasNuevoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlacasNuevoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlacasNuevoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlacasNuevoPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JLabel Año;
    private javax.swing.JTextField CampoAño;
    private javax.swing.JTextField CampoColor;
    private javax.swing.JTextField CampoCurp3;
    private javax.swing.JTextField CampoCurp5;
    private javax.swing.JTextField CampoLinea;
    private javax.swing.JTextField CampoModelo;
    private javax.swing.JTextField CampoNoSerie;
    private javax.swing.JButton Cancelar;
    private javax.swing.JLabel Color;
    private javax.swing.JLabel Curp4;
    private javax.swing.JPanel FondoGris4;
    private javax.swing.JLabel FotoGobSonora;
    private javax.swing.JLabel Linea;
    private javax.swing.JLabel Modelo;
    private javax.swing.JLabel NoSerie;
    private javax.swing.JLabel Opcional;
    private javax.swing.JLabel Opcional1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
