/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import Tools.Imagen;
import javax.swing.JFrame;

/**
 *
 * @author Arell
 */
public class PlacasNuevoPanel extends javax.swing.JFrame {

    /**
     * Creates new form PlacasNuevoPanel
     */
    public PlacasNuevoPanel() {
        initComponents();
        //Configurar Tamaño JFrame
        setTitle("Ventana de solicitud para Placas Nuevas");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
         // Configurar la Foto
        Imagen imagen = new Imagen();
        imagen.PintarImagen(FotoGobSonora, "src\\Pantallas\\GobSonora.jpg");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CampoCurp3 = new javax.swing.JTextField();
        Opcional = new javax.swing.JLabel();
        Curp4 = new javax.swing.JLabel();
        CampoCurp5 = new javax.swing.JTextField();
        Opcional1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        FondoGris4 = new javax.swing.JPanel();
        FotoGobSonora = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Curp = new javax.swing.JLabel();
        CampoCurp = new javax.swing.JTextField();
        Aceptar = new javax.swing.JButton();
        Curp2 = new javax.swing.JLabel();
        Curp3 = new javax.swing.JLabel();
        CampoCurp2 = new javax.swing.JTextField();
        CampoCurp4 = new javax.swing.JTextField();
        Cancelar2 = new javax.swing.JButton();
        Curp5 = new javax.swing.JLabel();
        CampoCurp6 = new javax.swing.JTextField();

        CampoCurp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCurp3ActionPerformed(evt);
            }
        });

        Opcional.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        Opcional.setForeground(new java.awt.Color(255, 51, 51));
        Opcional.setText("Renovar Licencia");

        Curp4.setBackground(new java.awt.Color(153, 153, 153));
        Curp4.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        Curp4.setText("Modelo");
        Curp4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Opcional1.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        Opcional1.setForeground(new java.awt.Color(255, 51, 51));
        Opcional1.setText("Vigente");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FondoGris4.setBackground(new java.awt.Color(0, 51, 51));

        FotoGobSonora.setBackground(new java.awt.Color(255, 255, 255));
        FotoGobSonora.setForeground(new java.awt.Color(255, 255, 255));
        FotoGobSonora.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setBackground(new java.awt.Color(0, 51, 51));
        jLabel4.setFont(new java.awt.Font("Roboto", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Datos del Automovil");

        javax.swing.GroupLayout FondoGris4Layout = new javax.swing.GroupLayout(FondoGris4);
        FondoGris4.setLayout(FondoGris4Layout);
        FondoGris4Layout.setHorizontalGroup(
            FondoGris4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoGris4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FotoGobSonora, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        FondoGris4Layout.setVerticalGroup(
            FondoGris4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoGris4Layout.createSequentialGroup()
                .addGroup(FondoGris4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoGris4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(FotoGobSonora, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FondoGris4Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel4)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(FondoGris4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 511, -1));

        Curp.setBackground(new java.awt.Color(153, 153, 153));
        Curp.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        Curp.setText("Marca");
        Curp.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(Curp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 110, -1));

        CampoCurp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCurpActionPerformed(evt);
            }
        });
        jPanel1.add(CampoCurp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 161, -1));

        Aceptar.setBackground(new java.awt.Color(0, 255, 51));
        Aceptar.setFont(new java.awt.Font("Roboto Black", 3, 12)); // NOI18N
        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });
        jPanel1.add(Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 310, 112, 30));

        Curp2.setBackground(new java.awt.Color(153, 153, 153));
        Curp2.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        Curp2.setText("No. Serie");
        Curp2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(Curp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 110, -1));

        Curp3.setBackground(new java.awt.Color(153, 153, 153));
        Curp3.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        Curp3.setText("Modelo");
        Curp3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(Curp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 110, -1));

        CampoCurp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCurp2ActionPerformed(evt);
            }
        });
        jPanel1.add(CampoCurp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 161, -1));

        CampoCurp4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCurp4ActionPerformed(evt);
            }
        });
        jPanel1.add(CampoCurp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 161, -1));

        Cancelar2.setBackground(new java.awt.Color(255, 0, 0));
        Cancelar2.setFont(new java.awt.Font("Roboto Black", 3, 12)); // NOI18N
        Cancelar2.setText("Cancelar");
        Cancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelar2ActionPerformed(evt);
            }
        });
        jPanel1.add(Cancelar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 101, 30));

        Curp5.setBackground(new java.awt.Color(153, 153, 153));
        Curp5.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        Curp5.setText("Color");
        Curp5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(Curp5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 110, -1));

        CampoCurp6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCurp6ActionPerformed(evt);
            }
        });
        jPanel1.add(CampoCurp6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 161, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoCurpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCurpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCurpActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
         PagoGeneradoPlacasPanel placas = new PagoGeneradoPlacasPanel();
        placas.setVisible(true);
    }//GEN-LAST:event_AceptarActionPerformed

    private void CampoCurp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCurp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCurp2ActionPerformed

    private void CampoCurp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCurp3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCurp3ActionPerformed

    private void CampoCurp4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCurp4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCurp4ActionPerformed

    private void Cancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar2ActionPerformed
        // Cerrar el JFrame actual
        this.dispose();
    }//GEN-LAST:event_Cancelar2ActionPerformed

    private void CampoCurp6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCurp6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCurp6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlacasNuevoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlacasNuevoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlacasNuevoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlacasNuevoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlacasNuevoPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JTextField CampoCurp;
    private javax.swing.JTextField CampoCurp2;
    private javax.swing.JTextField CampoCurp3;
    private javax.swing.JTextField CampoCurp4;
    private javax.swing.JTextField CampoCurp5;
    private javax.swing.JTextField CampoCurp6;
    private javax.swing.JButton Cancelar2;
    private javax.swing.JLabel Curp;
    private javax.swing.JLabel Curp2;
    private javax.swing.JLabel Curp3;
    private javax.swing.JLabel Curp4;
    private javax.swing.JLabel Curp5;
    private javax.swing.JPanel FondoGris4;
    private javax.swing.JLabel FotoGobSonora;
    private javax.swing.JLabel Opcional;
    private javax.swing.JLabel Opcional1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
